name: Run Tests for Channel

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  produce_consume_single_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test produce_consume_single_task
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: produce_consume_single_task

  produce_with_overflow_from_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test produce_with_overflow_from_task
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: produce_with_overflow_from_task

  try_consume_from_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test try_consume_from_task
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: try_consume_from_task

  multiple_producers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test multiple_producers
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: multiple_producers

  multiple_consumers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test multiple_consumers
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: multiple_consumers

  concurrency_and_stress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test concurrency_and_stress
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: concurrency_and_stress

  produce_with_overflow_from_isr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test produce_with_overflow_from_isr
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: produce_with_overflow_from_isr
          timeout: 15s

  try_consume_from_isr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test try_consume_from_isr
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: channel
          test-name: try_consume_from_isr
          timeout: 15s
