name: Run Tests for Mutex

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test basic
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: mutex
          test-name: basic
        
  stress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test stress
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: mutex
          test-name: stress

  priority:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test priority
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: mutex
          test-name: priority

  poison:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test poison
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: mutex
          test-name: poison