name: Run Tests for Semaphore

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  initialization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test initialization
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: initialization
          
  down_0_then_try_down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test down_0_then_try_down
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: down_0_then_try_down

  up_max_then_try_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test up_max_then_try_up
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: up_max_then_try_up
  
  _4_tasks_down_contend_init_3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test 4_tasks_down_contend_init_3
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: 4_tasks_down_contend_init_3

  init_0_blocking_down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test init_0_blocking_down
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: init_0_blocking_down

  try_up_ok_then_err:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test try_up_ok_then_err
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: try_up_ok_then_err

  try_down_ok_then_err:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test try_down_ok_then_err
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: try_down_ok_then_err

  _2_tasks_5_down_5_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test 2_tasks_5_down_5_up
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: 2_tasks_5_down_5_up

  _10_tasks_100_up_down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test 10_tasks_100_up_down
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: sync
          sub-category: semaphore
          test-name: 10_tasks_100_up_down


